// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbajhimjvdgrildaorvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYWpoaW1qdmRncmlsZGFvcnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTk1MDgsImV4cCI6MjA2Mzc5NTUwOH0.TOI-URoH-z1kEql35Ltcl9zmQxVLjoL4m8N6k5EGkU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);